accounts/urls.py
from django.urls import path

from . import views


app_name='accounts'

urlpatterns = [
    path('', views.login_view,name="login"),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view,name = 'logout'),
    path('profile/',views.profile, name = 'profile'),
]

bentomap/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('food/', views.food, name = 'food'),
    path('place/',views.place, name = 'place'),
    path('index/',views.index),
    path('accounts/',include('accounts.urls'), name = 'account'),


]

urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User



# Create your models here.
# class UserProfile(models.Model):
# 	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name = 'pds'E)
# 	userscore = models.IntegerField(default='0')

# 	def __str__(self):
#         return self.title
class User_extend(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
	rating = models.FloatField(default = 10,blank = True)

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from foodevent.models import FoodEvent, Place, TakeFood
from accounts.models import User_extend
from django.contrib.auth.decorators import login_required
# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request,user)
            # return redirect('articles:list')
            return redirect('../')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user
            user = form.get_user()
            login(request,user)
            return redirect('../')
        else:
            return redirect("../")
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    logout(request)
    return redirect('../')
@login_required(login_url='/accounts/')
def profile(request):
    if request.user.is_authenticated:
        name = request.user.username
        user = request.user
        try:
            new_user = User_extend.objects.get(user=user)
        except:
            new_user = User_extend.objects.create(user=user,rating=0)
        history = TakeFood.objects.all()
        myhis = []
        mytake = []
        rat = 10
        for his in history:
            if his.food.provider == request.user:
                myhis.append(his)
        for his in history:
            if his.taker == request.user:
                mytake.append(his)
                rat = rat+his.rating
        if len(mytake) != 0:
            rat = rat/(len(mytake)+1)
        User_extend.objects.filter(user=user).update(rating=rat)
    return render(request,"accounts/profile.html",locals())

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="zh">
{% load  staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>剩食地圖</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'fonts/font-awesome/css/font-awesome.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
	<!-- Navigation-->
  <nav id="menu" class="navbar navbar-default navbar-fixed-top">
	  <div class="container"> 
    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <a class="navbar-brand page-scroll" href="">NTU<br>Remaining Food<br>Map</a>
			</div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="{% url 'home' %}" class="page-scroll">Home</a></li>
	        <li><a href="#map-section" class="page-scroll">Map</a></li>
	        <li><a href="{% url 'food' %}" class="page-scroll">Food Event</a></li>
	        <li><a href="/accounts/" class="page-scroll">Account</a></li>
	        <li><a href="/accounts/profile/" class="page-scroll">profile</a></li>
	        {% if user.is_authenticated %}
			     <li> <h5 style= "margin-top: 17px;">Hi {{ user.username }}</h5></li>
			{% else %}
			        
			        <li><h5 style= "margin-top: 17px;">You are not logged in</h5></li>
			        
			{% endif %}
	       
	      </ul>
	    </div>
	  </div>
	</nav>
	<section id="map-section">
		<div class="container">
				<h1>Login</h1>
				  <form action="{% url 'accounts:login' %}" method="post" >
				  	{% csrf_token %}
				  		{{ form }}
				  	{% if request.GET.next %}
					  	<input type="hidden" name="next" value="{{request.GET.next}}">
				  	{% endif %}
				  	<input type="submit" value="Login">
				  </form>
				  <br> <br>
				  <button onclick="location.href='/accounts/logout'">Logout</button>
			     <br> <br>
				  <div class="signup-btn">
				  	<button onclick="location.href='{% url "accounts:signup" %}'" type="button">Create An Account</button>
				  </div>
		</div>
	</section>
</body>

</html>

accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="zh">
{% load  staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <title>剩食地圖</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'fonts/font-awesome/css/font-awesome.css' %}" rel="stylesheet" type="text/css" />


</head>
<body>
  <style type="text/css">
    .box{
      width: 42%;
      padding: 10px;
      padding-left: 2.5%;
      border: 2px solid gray;
      margin: 0;
      display: inline-block;
      float: left;
      margin: 4%;
    }
    .myprofile {
      border-left:100px;
      height: 200px;
      width: 100%;
      background-size: contain;
      background-color: white;
      z-index:-1!important;
    }

    .myprofile img {
      width: 150px;
      height: 150px;
      /*border-radius: 10%;*/
      padding: 0.2rem;
      margin: 20px;
      background: white;
      /*border:10px;*/
      /*border-style: solid;*/
      display: inline;
      /*border-color: white;*/
    }
    .myprofile-container {
      background-color: rgba(255,255,255,0.2);
    }
    .profile_img{
      display: inline;
    }
  </style>
  <nav id="menu" class="navbar navbar-default navbar-fixed-top">
    <div class="container"> 
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand page-scroll" href="">NTU<br>Remaining Food<br>Map</a>
      </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'home' %}" class="page-scroll">Home</a></li>
          <li><a href="#map-section" class="page-scroll">Map</a></li>
          <li><a href="{% url 'food' %}" class="page-scroll">Food Event</a></li>
          <li><a href="/accounts/" class="page-scroll">Account</a></li>
          <li><a href="/accounts/profile/" class="page-scroll">profile</a></li>
          {% if user.is_authenticated %}
           <li> <h5 style= "margin-top: 17px;">Hi {{ user.username }}</h5></li>
      {% else %}
              
              <li><h5 style= "margin-top: 17px;">You are not logged in</h5></li>
              
      {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <br><br><br><br><br><br><br>
  <div class="container">
        <div class = "myprofile">
              <span><img src="../../static/img/profile_image.png" alt="myprofile" style="float:left;">
                {% if request.user.is_authenticated %}
                  &nbsp;&nbsp;<h2>帳號：{{user.username}}</h2><br> <h3>積分：{{new_user.rating}}<h3>
                {% else %}
                 <h1><span>You are not login yet!</h1></span>
                {% endif %}
              </span>

          </div>
  </div>
  <br><br>
  <div class="container">
    <div class ="box">
      {% if request.user.is_authenticated %}
      <h3>我提供的食物</h3>
        {% for his in myhis %}
          <h5>歷史紀錄：<br>  領取者：{{ his.taker}}&nbsp;&nbsp;積分：{{his.rating}}</h5>
        {% endfor%}
      {% endif %}
    </div>
    <div class = "box">
      {% if request.user.is_authenticated %}
      <h3>我領取的食物</h3>
        {% for take in mytake %}
          <h5>歷史紀錄：<br> 提供者：{{ take.food.provider}}&nbsp;&nbsp;積分：{{take.rating}}</h5>
        {% endfor%}
      {% endif %}
    </div>
  </div>
  </body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="zh">
{% load  staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>剩食地圖</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'fonts/font-awesome/css/font-awesome.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
	<!-- Navigation-->
  <nav id="menu" class="navbar navbar-default navbar-fixed-top">
	  <div class="container"> 
    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <a class="navbar-brand page-scroll" href="">NTU<br>Remaining Food<br>Map</a>
			</div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="{% url 'home' %}" class="page-scroll">Home</a></li>
	        <li><a href="#map-section" class="page-scroll">Map</a></li>
	        <li><a href="{% url 'food' %}" class="page-scroll">Food Event</a></li>
	        <li><a href="/accounts/" class="page-scroll">Account</a></li>
	        <li><a href="/accounts/profile/" class="page-scroll">profile</a></li>
	        {% if user.is_authenticated %}
			     <li> <h5 style= "margin-top: 17px;">Hi {{ user.username }}</h5></li>
			{% else %}
			        
			        <li><h5 style= "margin-top: 17px;">You are not logged in</h5></li>
			        
			{% endif %}
	      </ul>
	    </div>
	  </div>
	</nav>
	<section id="map-section" class="text-center">
		<div class="container">
			<div class="row">
				<form method="post">
			        {% csrf_token %}
			        {{ form.as_p }}
			        <button type="submit">Sign up</button>
		        </form>
		        {% if user.is_authenticated %}
			        <center>
			            <p style="font-size:13pt">Hi {{ user.username }}!
			            <button onclick="location.href='/accounts/logout'">Logout</button>
			            </p>
			        </center>
			    {% else %}
			        <center>
			        <p style="font-size:13pt">You are not logged in.
			            <button onclick="location.href='/accounts/login'">Login</button></p>
			        </center>
			    {% endif %}
			</div>
		</div>
	</section>
</body>

</html>